### ISSUE TITLE
Blue moving box in bottom right corner never leaves

### ISSUE THREAD

**Issue by OhGodAGod** [SteamAchievementNotifier/SteamAchievementNotifier#50] opened 2024-03-21 10:46 UTC
I'm currently using the latest version (1.85.6, also tested on 1.85.5 and same thing happened), and as much as I like your program I am getting a perisistant blue shifting box in my bottom right hand corner of the screen that never leaves no matter what other applications I have open, no matter if it's already tracking a game, even after I reset the app.
![3](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/164337428/013f7088-a3ae-4aff-a4d1-317152bd46ba)
![1](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/164337428/06c7657f-840d-4fd6-97e6-6e78fe413eff)
![2](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/164337428/a4fae1ba-4138-405e-9317-c42972580888)

**Comment by SteamAchievementNotifier** [comment] 2024-03-22 00:06
Hey @OhGodAGod,

Unfortunately, this seems a common issue with V1.85. Usually, it indicates there is an error that is preventing achievement data from being loaded from the Steam Web API (which should show in **Settings** > **Open App Log**).

The issue is usually resolved by fully restarting the app (via *System Tray* > *Exit*, then relaunching), but if it's continually happening for a specific game (or all games) without successfully loading the data, let me know if you can see any errors in the **App Log**. Just make sure to obscure your API Key if you're providing screenshots of the log!

As it stands, I'm not planning to update V1.85 past the current version, as I am very close to publicly releasing the next major version of Steam Achievement Notifier, which has been in the works for some time and is currently in Closed Alpha - hence why there has been a lack of updates to the currently available versions! I haven't seen (or had any reports) of this issue happening in the new version, so once released, it should be a bit more reliable - plus, there's a lot of brand new features and fixes included, so check back soon!

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-05-08 21:47
Hey @OhGodAGod,

V1.9 has now been released, so you shouldn't get this issue anymore. I'll close this as it's only relevant to a previous version of SAN, but please let me know if you have any further issues in future with the new release.

Thanks!

**Closed by SteamAchievementNotifier** 2024-05-08 21:47 UTC
