### ISSUE TITLE
I'm receiving this steam achievement notifier error when shutting down Windows 11 all of a sudden

### ISSUE THREAD

**Issue by vizionblind** [SteamAchievementNotifier/SteamAchievementNotifier#73] opened 2024-10-23 03:22 UTC
### Has this issue previously been reported?

- [X] This issue has not been previously reported

### Platform

Windows

### Version

1.9.14

### Bug Details

Per the image, this is the error I receive when shutting down windows 11. Nothing has changed on my end in the past few days on my system so I'm curious what this means and how to resolve it

![Screenshot 2024-10-22 232142](https://github.com/user-attachments/assets/6525db4e-5aff-4d18-a573-cbeb77aac8b0)

**Comment by SteamAchievementNotifier** [comment] 2024-10-23 14:42
Hey @vizionblind,

I included a potential fix for this in a previous release, but obviously it is still an issue in your case. I can't reproduce this error myself, but I've looked up some other causes and will add another suggested potential fix in V1.9.15.

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-11-21 17:38
Hey again @vizionblind ,

I've changed what I can in V1.9.15, so I'll close this issue. Let me know if it's still a problem.

Thanks!

**Closed** 2024-11-21 17:38 UTC
Labels: bug
