### ISSUE TITLE
After I afk for some time, the notifier wont work

### ISSUE THREAD

**Issue by AoiRingoz** [SteamAchievementNotifier/SteamAchievementNotifier#3] opened 2021-07-25 05:37 UTC
I need to close and open the notifier again to start working

**Comment by SteamAchievementNotifier** [comment] 2021-08-05 15:43
Hi AoiRingoz,

This is an issue that I'm aware of. I'll be looking into it asap. In the meantime, if you don't see the "Now tracking achievements for <currentgame>" prompt when starting a game, the app will need to be exited from the system tray and restarted.

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2021-08-06 21:00
Hi again @AoiRingoz,

I've just released [Version 1.5](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.5) which includes a patch to fix this issue. Just download "_SANGUI.zip_" and run "_Version 1.5 Patch.bat_".

Thanks for reporting!

**Comment by SteamAchievementNotifier** [comment] 2021-08-07 11:37
Version 1.5 fixes this issue, but upon release (06/08/21), I discovered another big issue caused by fixing the previous one...

I will update with Version 1.5 asap. For now (as mentioned above), if you don't see the "Now tracking achievements for `currentgame`" prompt when starting a game, the app will need to be exited from the system tray and restarted.

**Comment by SteamAchievementNotifier** [comment] 2021-08-07 16:52
Hi again AoiRingoz,

This issue _should_ now be resolved in the [newest release](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.5). Please let me know if you have any further issues. I'll keep this issue open until I can confirm all is working as expected.

Thanks!

**Comment by AoiRingoz** [comment] 2021-08-08 03:08
Okay the plugin is almost perfect, there is just one issue, sometimes a windows powershell window popup for 0.2 seconds, its not too bad

**Comment by SteamAchievementNotifier** [comment] 2021-08-10 10:01
Hi again AioRingoz,

It will pop up with a console window for a very brief time when not tracking a game (however, when in game, no console window should show at any time). This is unfortunately due to the fix that was implemented for 1.5 (and Powershell not able to hide windows as effectively as it should...). The next release will likely be bug fixes and general QoL updates, so check back soon for a new release.

Thanks again for checking it out!

**Closed by SteamAchievementNotifier** 2021-08-10 10:01 UTC
