### ISSUE TITLE
"No Game Detected" while playing games

### ISSUE THREAD

**Issue by Timotit** [SteamAchievementNotifier/SteamAchievementNotifier#51] opened 2024-04-13 18:13 UTC
I'm using EndeavourOS and version 1.84 of SAN. Everytime I open a game it says No Game Detected. I followed the setup guide and set my steam profile to public, but it still doesn't work.
![Screenshot_20240413_201107](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/assets/127035886/2c0952d7-faa8-4e7d-8369-665faf4bf2cf)

**Comment by SteamAchievementNotifier** [comment] 2024-04-14 08:45
Hey @Timotit,

Despite only being officially tested on Ubuntu, V1.84 has seemed to work for others using distros such as PopOS, Arch, Manjaro etc., so not sure why it wouldn't work on EndeavourOS.

The next major update - V1.9 - has just entered closed Beta status, and users have reported that it is mostly working with EndeavourOS. As V1.84 is no longer maintained, and as I am currently looking for Linux testers, you're welcome to join the Discord - I can then give you access to test the latest version if this is something you'd be interested in doing?

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-05-08 21:49
Hey @Timotit,

V1.9 has now been released, which also has a Linux version. Please try downloading the [latest AppImage](https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.9.0) and let me know if this resolves the issue.

Thanks!

**Comment by Roman-AE** [comment] 2024-05-09 06:33
Hello. I am using Ubuntu 24.04. The problem is still here with latest V1.9 appimage version. Trying with native (deb) Steam, flatpak Steam, manually linked game. Nothing works. No game detected.

**Comment by SteamAchievementNotifier** [comment] 2024-05-09 11:40
Hey @Roman-AE,

The V1.9 AppImage has been primarily tested on Ubuntu using the standard Steam `.deb` installer, so it shouldn't cause any issues, unless it's been installed in a non-standard way.

If you're able to get the app to open without errors, that means that the initial checks for a valid Steam path have passed, so it's able to find your installation at least.

I have had a report of a similar issue - no games being detected after initially launching the app - and it was advised that using the **Settings** > **Reset App** option resolved it. Could you try this and let me know?

Thanks!

**Comment by Roman-AE** [comment] 2024-05-13 12:24
Hello @SteamAchievementNotifier. Sorry fo delay.
Can't get it to reliable working. Completely reinstall Steam. Noticed some things. 
SteamAchievementNotifier expected Steam at this path (see that in app logs, gen1s - username): /home/gen1s/.local/share/Steam. However real Steam installation at /home/gen1s/.steam/debian-installation. Can't find where i can change Steam folder in SteamAchievementNofifier. So i create symlink.
Next thing is that SteamAchievementNofifier not working with games installed outside Steam folder. All my games installed on separate partition. Ok. Move some small games to Steam folder for testing.
Now when i start game there is Steam error message: game already running. When i click close on that message notification from SteamAchievementNofifier appearing (tracking game). In Steam game showing as started but actually game is not working. 
But for some game (one of three - Lego Builder's Journey) it's working normally. Game actually starting and notification from SteamAchievementNofifier appearing. Don't test if it actually tracking notification. When close game it's not autoreleasing, need to go to menu and choose "Options - Release game".
And that's all my progress for now.

**Comment by madmaxgrey** [comment] 2024-05-14 08:16
@Roman-AE hey can i ask you to unisntall steam completely and delete the .steam folder please after that reboot and resinstall steam then try and see if that works hopfully that should resolve the debian folder version,

**Comment by SteamAchievementNotifier** [comment] 2024-05-14 08:41
Hey @Roman-AE,

@madmaxgrey and myself have done some digging on this, and we've found that:

- Installing Steam on Ubuntu via the `.deb` installer available on the [Steam site](https://store.steampowered.com/about/) will create `~/.local/share/Steam` as normal
- Installing via `apt install steam` will create the `~/.steam/debian-installer` directory instead (without creating the directory in `~/.local/share/Steam`)

So I imagine the issue is that either you've installed Steam via `apt install steam`, or that you have multiple versions of Steam installed on your system. I'll add the `~/.steam/debian-installer` directory as a valid Steam directory for V1.9.1, which should be releasing within the next few days.

Once you've updated to the latest version, could you let me know if this resolves the issue?

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-05-14 17:08
Just to update Linux users - the "steampath" variable will now be automatically parsed from the `"SourceModInstallPath"` key in `~/.steam/registry.vdf` (minus `/steamapps\\sourcemods`) in V1.9.1, so it should now be able to find a valid Steam path regardless of your distro.

For some reason, Valve have chosen to abandon writing most info to this file, but as this key is still written to, we can thankfully still use it.

Thanks!

**Comment by Roman-AE** [comment] 2024-05-14 18:15
@SteamAchievementNotifier @madmaxgrey thanks for your help. Install Steam from Valve deb and now it works. Still no autorelease game after exit but it'not so critical.

**Comment by SteamAchievementNotifier** [comment] 2024-05-15 07:51
Hey again @Roman-AE,

If certain games are having issues automatically releasing, please try increasing the value of the **Settings** > **Release Delay** option. This should allow more time for Steam to reset the **AppID** of the game to `0`, which will then allow SAN to automatically release it.

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-05-24 20:50
Closing as this is now resolved in V1.9.1 and above.

**Closed by SteamAchievementNotifier** 2024-05-24 20:50 UTC
