### ISSUE TITLE
Achievement Popups Stop Worrking Seemingly At Random

### ISSUE THREAD

**Issue by xyifer12** [SteamAchievementNotifier/SteamAchievementNotifier#20] opened 2022-08-06 07:26 UTC
Issue: For an unknown reason, SAN will no longer show trophy notifications even if a test popup button is clicked. The software will open from tray and is otherwise functional, but popups will not work until SAN is restarted.

Tested:
Hide Steam Notification enabled and disabled, made no difference.
Disable Hardware Acceleration enabled and disabled, made no difference.
Changed from 1.84 to beta, made no difference.

Additional Information: The last game I played with successful achievement popups was Alien Swarm: Reactive Drop. During gameplay I unlocked 10 achievements with 7 screenshots being taken automatically. The next game I played was Monster Hunter Rise, no achievements earned. I then played a non-Steam game. Now when I test the popup button, nothing happens.

I run Windows 10 Pro 21H2, x64. GeForce Experience is always passively recording.

**Comment by SteamAchievementNotifier** [comment] 2022-08-06 11:57
Hey @xyifer12,

Do notifications resume normally if the app is exited/restarted? And does the issue only occur after switching between games? I haven't had any other reports of similar behaviour recently, so if it persists, I'd advise clearing your app data and restarting via SANLauncher:

- Go to Settings > Reset App to Default > Reset

> To restore your previous configuration, copy `config.json` (located in `%localappdata%\Temp\SAN1.8Backup\store`) and replace the one located in `%localappdata%\Steam Achievement Notifier (V1.8)\store`.

Also, some users have reported issues after waking from sleep mode while leaving the app running, but I've not been able to replicate that issue myself.

If you're still having issues, I'd suggest looking at the Console to check for any errors. You can access it by pressing `CTRL + Shift + i` in the main app window - you may need to click `>>` (next to the `Elements` button at the top) and select `Console` from the dropdown menu to view it.

Thanks!

**Comment by xyifer12** [comment] 2022-08-07 10:43
The notifications do function after SAN is closed and re-opened. The issue does not only occur after switching between games, it sometimes happens between play sessions of a single game. I have cleared my AppData folder of any SAN folders and reset SAN settings to default before reconfiguring SAN, this did not help.

I do not use hibernation or sleep mode on my PC.

Here is the chain of events for the most recent instance of the issue tonight:
Turn on computer.
Log into Windows.
Start Discord.
Start SAN (1.84 beta).
Start DS4Windows.
Start Steam.
Play Monster Hunter Rise, no achievements earned.
Close Monster Hunter Rise.
Test SAN, test popup doesn't work.

When I saw that the issue had occurred I opened the console in SAN and the most recent line is "Main Test Notification added to queue. san1.8.js:408" with a number indicating how many times I pressed the test button.

**Comment by SteamAchievementNotifier** [comment] 2022-08-07 14:50
Hey again @xyifer12,

It doesn't look like like you're doing anything that would cause SAN to stop functioning. I had personally encountered the issue where notifications would stop functioning after ~6-8 hours, but after updating some code, it doesn't seem to be happening for me any more. Although one difference I do see in comparison to my experience is that test notifications stop working as well.

I do have some suspicions on what could be causing it - i.e. the "setInterval()" method in Node JS, which SAN uses to check for Steam Web API updates, seems to stop working without errors after a while from what I've read from others - but I'm looking into changing the way that SAN checks achievement information in the next major version update.

I will be doing further updates in the Beta Channel before the next major release, so it may be worth checking whether these updates help with this particular issue. Update notes are usually posted on Discord, but I will let you know here when I've added anything relevant to this particular issue.

Thanks!

**Comment by roginilom** [comment] 2022-08-11 15:42
Hey, 

Just wanted  to let you know that I have exactly the same issue. 

> Also, some users have reported issues after waking from sleep mode while leaving the app running, but I've not been able to replicate that issue myself.

This one I get as well but it's rare. Sometimes it starts working again after a few restarts and when you earn a new achievement all of the old ones pop up as well, like 3-4 in a row.    Also when you test the popup sometimes only the rare achievement works for some reason.

**Comment by SteamAchievementNotifier** [comment] 2022-08-11 22:51
Hey @roginilom,

Thanks for letting me know. I know a few users have come across this issue before (myself included). I'm currently testing a solution to this issue that, if successful, will be released to the Beta Channel via the next App Revision (plus a bunch more fixes and QoL updates).

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2022-08-20 23:22
@xyifer12 @roginilom - I've updated the interval timers in the latest Beta Channel App Revision (BETA 0.5) which was released earlier today. If you want to test whether this issue is resolved with the new timers, join the Beta Channel via Settings > **Join Beta Channel**.

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2022-08-23 13:49
Hey again @xyifer12,

Awesome, thanks for letting me know! I'll also keep this open for any further related issues in the near future, but good to know it's now working as intended.

Thanks!

**Closed** 2022-09-23 18:24 UTC
