### ISSUE TITLE
Is it supposed to cause high CPU usage on WMI Provider Host?

### ISSUE THREAD

**Issue by WenexLJ** [SteamAchievementNotifier/SteamAchievementNotifier#7] opened 2021-09-11 02:07 UTC
Hey!

Been using your program, also not a first time I posted. You fixed the issue - with 1.6 version - with powershell window appearing every now and then. 

Recently though I noticed, that whenever I have your program running it causes constant CPU usage by WMI Provider Host. I can basically replicate it by closing and reopening the program 100% of the time, so there's no denial the program is the cause. My question would be if this is something that's supposed to happen technically speaking, or if it's unitentional action caused by your program. Or maybe it affects only me for whatever reasons unknown.

Anyway, it kinda do concern me in a long run, as I don't want my CPU to be constantly draining cycles, if it's not required to.

Would appreciate the answer, cheers!

![yfCMJU7](https://user-images.githubusercontent.com/88956472/132932766-c1e659c0-6eb6-480d-815f-36f86c693258.png)

The process below WMI is also appearing with it as well. Both closes when I shutdown SteamAchivementNotifier

**Comment by PlageOne** [comment] 2021-09-18 18:04
Hi, 

No the problem is not only you, I just checked this with me and I also have about 8-10% perfromance loss. 
Thanks to my CPU, I don't notice this without further ado, but 10% power loss is a bit of a problem. 

My Rig: 

CPU: - I7 8700K @5GHz -
GPU: - MSI RTX 2080 TI Gaming X Trio -
RAM: - 16GB DDR4 @ 3200MHz -

Windows Version: 21H1 (Build: 19043.1165)

**Comment by WenexLJ** [comment] 2021-09-18 20:08
> Hi,
> 
> No the problem is not only you, I just checked this with me and I also have about 8-10% perfromance loss.
> Thanks to my CPU, I don't notice this without further ado, but 10% power loss is a bit of a problem.
> 
> My Rig:
> 
> CPU: - I7 8700K @5ghz -
> GPU: - MSI RTX 2080 TI Gaming X Trio -
> RAM: - 16GB DDR4 @ 3200MHz -
> 
> Windows Version: 21H1 (Build: 19043.1165)

Yeah, so for me it's rounding about 25% which is quite a lot. I'm using i5 9440f, GTX 1660 Ti, 16 GB DDR4 .

**Comment by SteamAchievementNotifier** [comment] 2021-12-03 09:47
Hey again WenexLJ,

Just letting you know that Version 1.71 has been released now, which should resolved high CPU usage and does not affect WMI Provider Host. I'll close this issue, but let me know if you have any further issues with the newer version.

Thanks!

**Closed by SteamAchievementNotifier** 2021-12-03 09:47 UTC
