### ISSUE TITLE
Automatic Steam Screenshots are not triggering

### ISSUE THREAD

**Issue by Banjoei** [SteamAchievementNotifier/SteamAchievementNotifier#69] opened 2024-08-30 02:42 UTC
I'm very happy to say that the app does create screenshots with notification overlay perfectly fine, but Steam isn't capturing any screenshots when I obtain achievements. I was playing Risk of Rain, but no screenshots were on my Steam account afterwards.

**Comment by SteamAchievementNotifier** [comment] 2024-08-30 20:50
Hey @Banjoei ,

Just to make sure, I'm assuming you've enabled the **Take Steam Screenshot** option under **Settings** > **Media**?

If so, what keyboard layout are you using? I've tested the keypress functions on the standard UK layout, but YMMV with other configurations.

Also, if you're using a non-standard key in Steam to trigger screenshots, the mapping of some Steam keycodes are not very clearly documented, so I would advise testing setting your Steam screenshot key to something else and seeing whether it works. If so, if you could then let me know the affected key/layout, I can look into troubleshooting it.

Thanks!

**Comment by Banjoei** [comment] 2024-08-31 00:33
I assume that when the box is blue the option is checked. A checkmark would be nice for clarity, but if it is that then I've had it checked.
I use the Standard US layout, and my screenshot key is bound to F12, which I believe is the default key. If the app works by sending the standard key input, then you should probably include an option to change the key to whatever you have it bound, but I do have my key bound to the default with the US keyboard.

**Comment by SteamAchievementNotifier** [comment] 2024-08-31 08:29
Hey again @Banjoei ,

F12 should work, as this is the standard Steam screenshot key. If you had remapped it to a more obscure key, that's where issues might arise due to keyboard layouts etc.

There is no input for mapping the key in SAN as it reads the screenshot key directly from `localconfig.vdf`, located in Steam's installation files.

I'll test whether this is still working my side and if not, I can look into providing a fix for the next release.

Thanks!

**Comment by Banjoei** [comment] 2024-08-31 22:10
Thank you for looking into it! Please let me know if you find anything odd. It's confusing that I have the default bind yet it's not working, I wonder what could've caused that. I am using the latest release btw.

**Comment by Banjoei** [comment] 2024-08-31 22:13
I believe I've found something that might be the issue. You mentioned how the key is read directly from `localconfig.vdf`, but that file is different per user. It would so happen to be that I have multiple accounts on the same device, as I use them for Family Sharing. Could it be one of the people I'm sharing the device with has a different bind and it's causing issues? More so, could it be the program is getting confused since it's finding multiple user folders?

**Comment by SteamAchievementNotifier** [comment] 2024-09-08 12:08
Hey @Banjoei,

I've tested Steam keybinds and they seem to be working fine.

In terms of whether different users affect the keybind, I have two users set up on my personal PC and have Family Sharing enabled between the two accounts. Both accounts are able to take Steam screenshots via SAN without issue, so I'm not sure that would cause any problems.

Once you get an achievement, you can check the **App Log** (via **Settings**) to see if any errors relating to triggering keybinds are appearing. If so, paste the error here and I can have a look into why this is happening for you.

Thanks!

**Comment by SteamAchievementNotifier** [comment] 2024-10-23 14:44
Hey @Banjoei,

I'll close this for now, but let me know if you're able to reproduce it and provide your App Log.

Thanks!

**Closed by SteamAchievementNotifier** 2024-10-23 14:44 UTC
Labels: bug
